name: Deploy to DigitalOcean App Platform

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && (github.event.workflow_run.head_branch == 'master') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_DEPLOYMENT_TOKEN }}

      - name: Create a new deployment
        run: doctl apps create-deployment ${{ secrets.DIGITAL_OCEAN_APP_ID }}
